### ISSUE TITLE
raise NotImplementedError()  NotImplementedError when I use tts 

### ISSUE THREAD

**Issue by hussam132** [kivy/plyer#567]
I want to make simple tts with plyer and kivy by learning from tutorials on YouTube
but I'm getting this error
```
raise NotImplementedError()
 NotImplementedError
```
this my main.py

```
from kivymd.app import MDApp
from kivy.lang import Builder
from plyer import battery, vibrator, tts
from kivymd.toast import toast


class MainApp(MDApp):
    def build(self):
        return Builder.load_file("main.kv")

    def speak_the_text(self, text):
        tts.speak(text)


MainApp().run()

```
and this my main.kv file

```
BoxLayout:
    orientation: 'vertical'

    MDTextField:
        text: "text"
        id: MDTextField_id
        size_hint: 1,.5

    MDRaisedButton:
        text: "speak"
        size_hint: 1,.5
        on_release:
            app.speak_the_text(MDTextField_id.text)

```

I want to know what's wrong in my code ??
